[package]
name = "ll"
version = "0.1.0"
authors = ["Iain Earl <synapse791@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
